### ISSUE TITLE
Using a comprehensive email validator

### ISSUE THREAD

**Issue by prateeknischal** [surajs1n/email-normalization#8]
Email addresses are a mess and have undergone multiple iterations. Using a more centrally managed validator for the [`util.EmailValidator`](https://github.com/surajs1n/email-normalization/blob/develop/src/main/java/util/EmailValidator.java) would eliminate the need of tracking all the weird cases. 

An ad-hoc implementation is included in [Java email validation regex](https://www.baeldung.com/java-email-validation-regex) or even better, using the [`EmailValidator`](https://commons.apache.org/proper/commons-validator/apidocs/org/apache/commons/validator/routines/EmailValidator.html) class from the Apache [commons-validator](https://commons.apache.org/proper/commons-validator/) might help.

**Comment by thinktrans** [comment]
EmailValidator is definitely a good choice as it supports even the Internationalized Email Addresses. 

If I may, I would like to request you to keep it as simple as this:
`<e-mail local part>@<domain name>`
Which can be implemented as 

For `<e-mail local part>` - Follow the guidelines by the "Universal Acceptance Steering Group" - UASG-026 - https://uasg.tech/download/uasg-028-considerations-for-naming-internationalized-email-mailboxes-en/

For `<domain name>`, you can follow any domain validation methodology using standard libraries, depending on your programming language. For the recent studies on the subject, follow the document UASG-018A - https://uasg.tech/download/uasg-018a-ua-compliance-of-some-programming-language-libraries-and-frameworks-en/.

**Comment by surajs1n** [comment]
This is a good suggestion @prateeknischal @thinktrans . Let me implement and push it into my next release. I will inform you once it is done.

**Comment by surajs1n** [comment]
This Pr has the fix: https://github.com/surajs1n/email-normalization/pull/10. Let me know if you have some other points to add.

**Comment by surajs1n** [comment]
PR is merged. Thus, closing the ticket.
