### ISSUE TITLE
Type mistake in README

### ISSUE THREAD

**Issue by garg-Megha** [surajs1n/email-normalization#9]
<img width="628" alt="image" src="https://user-images.githubusercontent.com/25024910/194314823-68f66a9b-5fa6-45b4-857b-00c9540b3ea9.png">
 
 
I was going through the readme file.  There is some typing mistake in the README.md file. 

Attaching screenshot for reference.

**Comment by surajs1n** [comment]
Thanks, @garg-Megha I have pushed the fix in this PR: https://github.com/surajs1n/email-normalization/pull/10. Do let me know if you find anything else too.
